### PR TITLE
added animated back ground

### PR DESCRIPTION
**Pull request by chiranjibismg**
Update issue #1

### CODE REVIEW

**Comment by chiranjibismg** [comment]
please check my PR for issue #1

**Comment by chiranjibismg** [comment]
Solved issue #3

**Comment by chiranjibismg** [comment]
Solved issue #15 Please check

**Comment by codingiitg** [comment]
Hey @chiranjibismg ,from next time try to make different PR's for each issue.

**Comment by chiranjibismg** [comment]
@codingiitg  I am sorry i am a bit unfamiliar with github. I will keep it in mind from next time.

**Comment by chiranjibismg** [comment]
Also how many points is the 'animated background issue ' worth ?

**Comment by codingiitg** [comment]
@chiranjibismg each issue in a beginner project is worth 1 point.

**Pull request closed without merging**
