### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by adv6273**

### CODE REVIEW

**Comment by codingiitg** [comment]
hey @adv6273 please mention the issue you have resolved in your PR.

**Comment by adv6273** [comment]
https://github.com/codingiitg/Codepeak-beginner-HTML-task/issues/15
@codingiitg

**Comment by codingiitg** [comment]
hey @adv6273 actually your background is somewhat fixed, can you add some animation too.

**Comment by adv6273** [comment]
yeah, I will add animation.
________________________________

**Comment by adv6273** [comment]
@codingiitg i have added the animation.

**Comment by adv6273** [comment]
u can check now @codingiitg

**Comment by adv6273** [comment]
@codingiitg you can check

**Comment by codingiitg** [comment]
Done!

**Pull request closed without merging**
